### ISSUE TITLE
Undefined Offset error in browser display

### ISSUE THREAD

**Issue by srajas02** [cbschuld/Browser.php#12]
```
     I have implemented browser.php on my project for tracking browsers and platform.When I check my browser  it will display all the browser name except
```

Google Chrome. It displays following error 
Undefined offset: 1 in D:\wamp\www\tracker202\assert\Browser.php on line 647.
please help me how to resolve these error?

**Comment by cbschuld** [comment]
Hi @srajas02 - sorry this is VERY old but this is fixed now
