### ISSUE TITLE
Remove closing PHP tag

### ISSUE THREAD

**Issue by IngwiePhoenix** [cbschuld/Browser.php#31]
As this class does not contain any HTML, accidential whitespaces in output due to them coming after the `?>` can be avoided by simply removing the closing tag. PHP does only requre an opening tag - and if it finds the file's end (EOF), then it will treat the file as complete.

Its just a simple thing I saw while reading the file.

**Comment by cbschuld** [comment]
@IngwiePhoenix 100% agreed; removed in current version
