### ISSUE TITLE
IE11 Detection broken

### ISSUE THREAD

**Issue by wonderboyjon** [cbschuld/Browser.php#34]
The recent commit 012d6043a9cdfddcbdf8e70d255041da4b33f961 broke detection of IE11. It no longer checks for 'trident' in the user agent string as it was before, and IE11 does not contain MSIE in the user agent string. This wrongly causes getBrowser() to return "Mozilla" instead of "Internet Explorer".

**Comment by cbschuld** [comment]
@wonderboyjon - this is all fixed in 1.9.4 which is dropping today; thanks for the heads up FOREVER ago - did not have enough time to really work on this project when you submitted the issue; my fault.
