### ISSUE TITLE
Please tag versions

### ISSUE THREAD

**Issue by misilot** [cbschuld/Browser.php#36]
Please create versions in github, so the project can work nicely with composer

**Comment by calmdev** [comment]
@cbschuld please tag a release.

**Comment by adrazich** [comment]
+1

**Comment by sbuckpesch** [comment]
+1 @cbschuld That's an easy one... Please just tag the repo, which will help a lot!

**Comment by misilot** [comment]
@cbschuld Is there any likelihood of tagging a release? Even something like 0.1?

**Comment by visavi** [comment]
+1 иначе приходится прописывать "minimum-stability": "dev

**Comment by RsD0p9BK** [comment]
+1

**Comment by visavi** [comment]
What is the problem? To create a tag, you need only 1-2 minutes

**Comment by PATROMO** [comment]
+1

**Comment by cbschuld** [comment]
@PATROMO @visavi @Krknv @visavi @misilot @sbuckpesch @adrazich @calmdev @misilot - understood 100%... I have not had a lot of cycles to take care of this until now.  I'm going to be making a lot of changes over the next week or so.  Sorry for the massive radio silence on the project; I am back into it!

**Comment by cbschuld** [comment]
v 1.9.1. was tagged but I'll work on some of the issues and get this more up-to-date and will be releasing other versions soon
