### ISSUE TITLE
all is empty at php 5.6...

### ISSUE THREAD

**Issue by PaykomanVll** [cbschuld/Browser.php#38]
Hello,

ok all work, fine.,
Great job, thanks!

**Comment by temp3r** [comment]
Same for me, doesnt work. php 5.6.12

**Comment by sunnyjayjay** [comment]
Agreed. Just returns blank.

**Comment by Shnoulle** [comment]
https://github.com/cbschuld/Browser.php/commit/a25a010b2f6420e1fe3b7923b9e6f21d094d5c0b

**Comment by cbschuld** [comment]
@temp3r @sunnyjayjay - I assume this is VERY legacy because this issue is old and PHP's accelerated into 7.2, 7.3 but wanted to find out if this is something we should even address now before I close it.

**Comment by cbschuld** [comment]
closing for now as it was a legacy issue; always happy to re-open and address

note:  the reason this is delayed was due to me not addressing these topics back when the issue was created
