### ISSUE TITLE
Identify PlayStation systems

### ISSUE THREAD

**Issue by IngwiePhoenix** [cbschuld/Browser.php#44]
The PlayStation 3, 4 and Vita web browser share a pretty simple structure:

```
Mozilla/5.0 (Playstation $version[;] $firmware) AppleWebkit(......)
```

`$version`: 3, 4, Vita
`$firmware`: X.XX (i.e. 3.55)

The PlayStation 3 has a semi-colon, appearently, whilst Vita and 4 do not.

To classify:

``` php
    const BROWSER_PLAYSTATION = "PlayStation";
    const PLATFORM_PLAYSTATION = "Sony PlayStation";
```

PS 3 and 4 are "Desktop" and not mobile. Vita is mobile.

Unfortunately I am not perfectly sure of the results for the PSP.

Could they be implemented?

**Comment by FootballFan141** [comment]
I realize this is issue is a year old but I'm learning GitHub by trying to help that is why I sent a pull request.

@IngwiePhoenix Try this code with my forked version 😃 

```
<?php
require 'lib/Browser.php';

$agent = $_SERVER['HTTP_USER_AGENT'];
$browser = new Browser($agent);
if ($browser->getBrowser() == Browser::BROWSER_PLAYSTATION) {
    echo "Browser = " . $browser->getBrowser();
    echo '<br>';
    echo "Version = " . $browser->getVersion();
    echo '<br>';
    echo "isMobile = " . ($browser->isMobile() ? 'true' : 'false');
    echo '<br>';
    echo "Platform = " . $browser->getPlatform();
}

?>
```

**Comment by Shnoulle** [comment]
Closed in https://github.com/cbschuld/Browser.php/commit/a57a9b91c423cc587c38af77a05b544c3e92902b

**Comment by cbschuld** [comment]
@IngwiePhoenix @FootballFan141 - was merged & all set; closing.
