### ISSUE TITLE
Wrong browser name

### ISSUE THREAD

**Issue by AdministAppz** [cbschuld/Browser.php#67]
https://github.com/cbschuld/Browser.php/blob/6bde9efb0b14a4917affe741500c29149419e491/lib/Browser.php#L100
Browser name fix:
    const BROWSER_VIVALDI = 'Vivaldi'; // https://vivaldi.com/

**Comment by adaxi** [comment]
I already submitted a PR for this #64

**Comment by cbschuld** [comment]
PR merged; closing...
