### ISSUE TITLE
Add support for Brave browser detection

### ISSUE THREAD

**Issue by Zaczero** [cbschuld/Browser.php#69]
So there is a browser called Brave which is based on the Chromium open-source.
Homepage: https://brave.com/

It's available on pretty much same OSes that Chrome is.
They are using a slightly changed User-Agent on Windows though *(haven't checked linux one yet)*.

Windows 10 x64: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/74.0.3729.157 Safari/537.36`

Looks like on android they are using same User-Agent as the mobile Chrome.

Android 9: `Mozilla/5.0 (Linux; Android 9; *device*) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36`

I think Browser.php should add support for `Brave Chrome` keyword in case they change their mobile User-Agent to match the Window's scheme so it's possible to disguise mobile Chrome from Brave.

**Comment by cbschuld** [comment]
@Zaczero can you help me understand how one would detect Brave on the Android; I do not see a reference to "Brave" anywhere in the useragent - I will add it but need some more understanding around the user agents it will kick out.

**Comment by Zaczero** [comment]
> 
> 
> @Zaczero can you help me understand how one would detect Brave on the Android; I do not see a reference to "Brave" anywhere in the useragent - I will add it but need some more understanding around the user agents it will kick out.

What I meant was to ignore the android user-agent for now until Brave changes it to the custom one (like they did on desktop).

**Comment by cbschuld** [comment]
@Zaczero - understood; sorry I was not following initially... I'll add support in 1.9.4 hopefully today if I can cut enough time to work on it.

**Comment by cbschuld** [comment]
@Zaczero this is in 1.9.4 which I'm setting up now
