### ISSUE TITLE
Composer best practices

### ISSUE THREAD

**Issue by romainneutron** [cbschuld/Browser.php#7]
Hello,

it would be nice to remove the `version` property of composer.json file and use git tag to release versions.

This way is the simplest way of providing stable version as long as a developement one.

**Comment by sbuckpesch** [comment]
+1 duplicates https://github.com/cbschuld/Browser.php/issues/36

**Comment by cbschuld** [comment]
@romainneutron - thanks, this is finally done (sorry, just getting time to work on this project again).  @sbuckpesch - thx for the marker... done.  Closing.
