### ISSUE TITLE
Support for Pale Moon (based on Mozilla Firefox)

### ISSUE THREAD

**Issue by juozaspo** [cbschuld/Browser.php#70]
There's an Open Source project called Pale Moon which primary is based earlier versions of Mozilla Firefox, now independly developed over time. Project home page: https://www.palemoon.org/

The browser mainly available on Windows & Linux platforms, other platforms are still developed.
Linux UA (Pale Moon 28.5.0): `Mozilla/5.0 (X11; Linux x86_64; rv:60.9) Gecko/20100101 Goanna/4.2 Firefox/60.9 PaleMoon/28.5.0`

**Comment by cbschuld** [comment]
@juozaspo - this is coming soon; should have a PR later today or tomorrow morning.

**Comment by cbschuld** [comment]
available in 1.9.3 - closing!  thx @juozaspo
