### ISSUE TITLE
Sync repository packagist.org

### ISSUE THREAD

**Issue by visavi** [cbschuld/Browser.php#72]
New version v1.9.1 is not on site
https://packagist.org/packages/cbschuld/browser.php
![screen](https://user-images.githubusercontent.com/826831/59843824-061aab80-9362-11e9-9c46-e0f358249cd3.png)

**Comment by cbschuld** [comment]
@visavi got that solved for now!  more updates coming in the next few days

**Comment by cbschuld** [comment]
need to reopen this to re-address the auto updates!

**Comment by cbschuld** [comment]
handled officially now!
