### ISSUE TITLE
Update demonstration website

### ISSUE THREAD

**Issue by peter279k** [cbschuld/Browser.php#73]
As title, it seems that the `http://localhost:3000/projects/browser-php-detecting-a-users-browser-from-php/` demonstration site should be updated.

It should have a global website on the Internet to be visible for everyone.

I can support this domain and demonstration website if @cbschuld wants to do this :).

**Comment by cbschuld** [comment]
@peter279k - thanks, I updated the location

I am going to updating the site more in the coming days as well

Thanks, Chris
