### ISSUE TITLE
1.9.1 Release seems to be 2.0? 

### ISSUE THREAD

**Issue by skerbis** [cbschuld/Browser.php#76]
https://github.com/cbschuld/Browser.php/releases/tag/1.9.1

**Comment by cbschuld** [comment]
hi @skerbis can you elaborate on that; do I have 2.0 in there somewhere?

**Comment by skerbis** [comment]
Hi, look in your release 1.9.1 browser.php. 
There you will finde @version 2.0 on line 7 

![Bildschirmfoto 2019-07-09 um 09 47 41](https://user-images.githubusercontent.com/791247/60869157-b88db200-a22e-11e9-8de2-1ef805d483f0.png)

**Comment by cbschuld** [comment]
@skerbis - bummer; 100%; sorry about that; I fixed the 1.9.1 tag; thanks!
