### ISSUE TITLE
some gaps

### ISSUE THREAD

**Issue by Yaffle** [cbschuld/Browser.php#8]
iPhone
unknown 
`Mozilla/5.0 (iPhone; CPU iPhone OS 6_1_4 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) CriOS/28.0.1500.16 Mobile/10B350 Safari/8536.25`

Safari
unknown 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/536.11 (KHTML, like Gecko) DumpRenderTree/0.0.0.0 Safari/536.11`

iPhone
28.0 
`Mozilla/5.0 (iPhone; CPU iPhone OS 6_1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) CriOS/28.0.1500.16 Mobile/10B142 Safari/8536.25`

Internet Explorer
9.0
`Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; HTC; Radar; Orange)`
("Mobile")

**Comment by cbschuld** [comment]
@Yaffle - this is ancient but finally addressed, all of these issues are covered.  @Marco129 's comment about the unknown in the Safari version I agree with.  These are all handled in 1.9.4 which will be available in an hour or so.  Thanks!
