### ISSUE TITLE
Edge is erroneously being detected as a Chrome

### ISSUE THREAD

**Issue by angelscabrerag** [cbschuld/Browser.php#89]
Hi, Edge is erroneously being detected as a Chrome (Browser::BROWSER_EDGE) .

Edge on Mac reports: Chrome
Edge on Windows reports: Chrome
Edge on Linux reports: Chrome

Edge v.79.0.309.71

Any help would be appreciated to show correct browser name.

**Comment by vidurb** [comment]
The new version of Edge (v79) is based on Chromium, and mimics Chrome's user-agent under certain conditions. That might be a possible explanation.

**Comment by GramThanos** [comment]
Additional info from my agents:

Microsoft Edge BETA (https://www.microsoftedgeinsider.com/):
 - About:
	- Version 81.0.416.41 (Official Build) beta (64 bit)
 - User-Agent:
	- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.83 Safari/537.36 Edg/81.0.416.41

Google Chrome:
 - About:
	- Version 80.0.3987.162 (Official Build) (64-bit)
 - User-Agent:
	- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36

**Comment by cbschuld** [comment]
@GramThanos thank you for the PR

@vidurb & @angelscabrerag - thank you for the help!
