### ISSUE TITLE
Edge Mobile detected as Chrome

### ISSUE THREAD

**Issue by peat85** [cbschuld/Browser.php#92]
(This is directly related to #89)

The new chrome-based Microsoft Edge on **mobile** is still detected as a Chrome Browser.

I tried this on Android 10 with the official Microsoft Edge App (https://play.google.com/store/apps/details?id=com.microsoft.emmx) (App-Version: `Edge 45.02.4.4931`)

The user agent is:  
`Mozilla/5.0 (Linux; Android 10; HRY-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/45.02.4.4931`

I think the `A` in the `EdgA` part seems to be the problem since the latest fix only checks for `Edg`.

---

This should probably also be tested for the official Apple App (https://apps.apple.com/us/app/microsoft-edge/id1288723196) which I'm currently not able to.

**Comment by cbschuld** [comment]
@peat85 - thanks ; fixing now.
